routes/web.php
<?php

Route::get('/', 'Site\PostController@index')->name('welcome');
Route::get('/blog', 'Site\PostController@blog')->name('blog');
Route::post('/blog/{post}/comments', 'Site\CommentController@store')->name('post.comments');
Route::get('/product/{category}', 'Site\PostController@category' )->name('category');
Route::get('/baca/{post}', 'Site\PostController@show')->name('post.show');
Route::get('/u/{user}', 'Site\PostController@user')->name('user');
Route::get('/t/{tag}', 'Site\PostController@tag')->name('tag');


Route::get('/contact', 'Site\ContactController@show')->name('contact');
Route::post('/contact',  'Site\ContactController@mailToAdmin');

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/settings', 'Admin\SettingController@index')->name('settings');
    Route::post('/settings', 'Admin\SettingController@store')->name('settings.store');
});

Route::get('/home', 'Admin\HomeController@index')->name('home');
// profile
Route::get('/home/edit-profile', 'Admin\HomeController@edit')->name('profile.edit');
Route::put('/home/edit-profile', 'Admin\HomeController@update');
Route::get('/profile', 'Admin\UserController@profile')->name('profile');

// image featur
Route::get('/home/imagemanager', 'Admin\HomeController@imageManager')->name('image.manager');
// Change password
Route::get('/change-password', 'Admin\UserController@showChangePasswordForm')->name('form.change.password');
Route::post('/change-password', 'Admin\UserController@changePassword')->name('change.password');
// User
Route::resource('/home/user', 'Admin\UserController');
Route::get('/home/user/confirm/{user}', 'Admin\UserController@confirm')->name('user.confirm');
// post
Route::resource('/home/blog', 'Admin\PostController');
Route::put('/home/blog/restore/{blog}', 'Admin\PostController@restore')->name('blog.restore');
Route::delete('/home/blog/force-destroy/{blog}', 'Admin\PostController@forceDestroy')->name('blog.force-destroy');
// Category
Route::resource('/home/category', 'Admin\CategoryController');
// Project Gallery
Route::resource('/home/gallery', 'Admin\ProjectController');
// Tags
Route::get('/home/tag', 'Admin\TagController@index')->name('tag.index');
Route::delete('/home/tag/{id}', 'Admin\TagController@destroy')->name('tag.destroy');
// Comments
Route::get('/home/comment', 'Admin\CommentController@index')->name('comment.index');
Route::delete('/home/comment/{id}', 'Admin\CommentController@destroy')->name('comment.destroy');
Route::get('phpinfo', function(){
    echo phpinfo();
});

resources/views/layouts/backend/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="/image/png" href="/frontend/images/favicon.png"/>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ \setting('app_name', 'Sinar Matahari Kaca') }} - @yield('title')</title>

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <!-- Styles -->
    {{-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> --}}
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/backend/css/bootstrap.min.css">
    <!--Custom css -->
    <link rel="stylesheet" href="/backend/css/custom.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/backend/fonts/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/backend/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
        folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/backend/css/skins/_all-skins.min.css">
    <!-- bootstrap wysihtml5 - text editor -->
    <!-- Jasny Bootstrap -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
    <!-- Datetimepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
    {{-- <link rel="stylesheet" href="/backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css"> --}}
    <!-- References: https://github.com/fancyapps/fancyBox -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
    @yield('style')
</head>

    @yield('content')
    
    <!-- jQuery 2.2.3 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <!-- Moment JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <!-- Datetimepicker -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/backend/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.min.js"></script>
    <!-- Jasny Bootstrap -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/backend/js/app.min.js"></script>
    {{-- <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });
    </script> --}}
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <script src="/vendor/laravel-filemanager/js/lfm.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    @yield('script-post')
    @yield('script-tags')
    @yield('script-category')
    @yield('script-user')
    @yield('script-pagination')
    @yield('gallery')
    @yield('script-lfm')
</body>
</html>

resources/views/layouts/backend/foot-note.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.3.6
    </div>
    <strong>Copyright &copy; 2019 {{ \setting('app_name') }} | <strong>template</strong> by <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong>
</footer>

resources/views/layouts/backend/navbar.blade.php
<header class="main-header">
        <!-- Logo -->
        <a href="{{ route('home') }}" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>SM</b>K</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>{{ \setting('app_name') }}</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
          <!-- Sidebar toggle button -->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
    
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{{ Auth::user()->avatar() }}" class="user-image" alt="User Image">
                  <span class="hidden-xs">{{ Auth::user()->name }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="{{ Auth::user()->avatar() }}" class="img-circle" alt="User Image">
    
                    <p>
                      {{ Auth::user()->name }} - {{ Auth::user()->roles->first()->display_name }}
                      {{-- <small>Member since Nov. 2012</small> --}}
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="{{ route('profile') }}" class="btn btn-default btn-flat"><i class="fa fa-user"></i> Profile</a>
                    </div>
                    <div class="pull-right">
                        <a href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();" class="btn btn-default btn-flat"><i class="fa fa-sign-out"></i> {{ __('Logout') }}</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
</header>

resources/views/layouts/backend/sidebar.blade.php
<aside class="main-sidebar">
<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
    <div class="pull-left image">
        <img src="{{ Auth::user()->avatar() }}" class="img-circle" alt="User Image">
    </div>
    <div class="pull-left info">
        <p>{{ Auth::user()->name }}</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
    </div>
    </div>

    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
    <li>
        <a href="{{ route('home') }}">
        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
    </li>
    <li class="treeview">
        <a href="#">
        <i class="fa fa-folder"></i>
        <span>Blog</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
        </a>
        <ul class="treeview-menu">
        <li><a href="{{ route('blog.index') }}"><i class="fa fa-list" style="color:orange"></i> Semua list artikel</a></li>
        <li><a href="{{ route('blog.create') }}"><i class="fa fa-pencil" style="color:orange"></i> Tambah artikel baru</a></li>
        </ul>
    </li>
    @if(check_user_permissions(request(), "Category@index"))
    <li class="treeview">
        <a href="#">
        <i class="fa fa-folder"></i>
        <span>Kategorisasi</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
        </a>
        <ul class="treeview-menu">
        <li><a href="{{ route('category.index') }}"><i class="fa fa-list" style="color:orange"></i> Semua Kategori</a></li>
        <li><a href="{{ route('category.create') }}"><i class="fa fa-pencil" style="color:orange"></i> Buat kategori baru</a></li>
        </ul>
    </li>
    @endif
    @if(check_user_permissions(request(), "User@index"))
    <li class="treeview">
        <a href="#">
        <i class="fa fa-folder"></i>
        <span>Pengguna / User</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
        </a>
        <ul class="treeview-menu">
        <li><a href="{{ route('user.index') }}"><i class="fa fa-users" style="color:orange"></i> Semua pengguna</a></li>
        <li><a href="{{ route('user.create') }}"><i class="fa fa-user-plus" style="color:orange"></i> Tambah pengguna baru</a></li>
        </ul>
    </li>
    @endif
    @if(check_user_permissions(request(), "Project@index"))
    <li><a href="{{ route('tag.index') }}"><i class="fa fa-tags"></i> <span>Tags</span></a></li>
    <li><a href="{{ route('comment.index') }}"><i class="fa fa-comments"></i> <span>Komentar</span></a></li>
    <li><a href="{{ route('gallery.index') }}"><i class="fa fa-image"></i> <span>Galeri Proyek</span></a></li>
    @endif
    <li><a href="{{ route('image.manager') }}"><i class="fa fa-file-image-o"></i> <span>Pengatur Gambar</span></a></li>
    <li><a href="{{ route('profile.edit') }}"><i class="fa fa-id-card"></i> <span>Edit profil</span></a></li>
    <li><a href="{{ route('form.change.password') }}"><i class="fa fa-unlock-alt"></i> <span>Ubah kata sandi</span></a></li>
    @if(check_user_permissions(request(), "Setting@index"))
    <li><a href="{{ route('settings') }}"><i class="fa fa-cog"></i> <span>Pengaturan aplikasi</span></a></li>
    @endif
    </ul>
</section>
<!-- /.sidebar -->
</aside>