routes/web.php
<?php

Route::get('/', 'Site\PostController@index')->name('welcome');
Route::get('/blog', 'Site\PostController@blog')->name('blog');
Route::post('/blog/{post}/comments', 'Site\CommentController@store')->name('post.comments');
Route::get('/product/{category}', 'Site\PostController@category' )->name('category');
Route::get('/baca/{post}', 'Site\PostController@show')->name('post.show');
Route::get('/u/{user}', 'Site\PostController@user')->name('user');
Route::get('/t/{tag}', 'Site\PostController@tag')->name('tag');


Route::get('/contact', 'Site\ContactController@show')->name('contact');
Route::post('/contact',  'Site\ContactController@mailToAdmin');

Auth::routes(['verify' => true]);

Route::group(['middleware' => 'auth'], function () {
    Route::get('/settings', 'Admin\SettingController@index')->name('settings');
    Route::post('/settings', 'Admin\SettingController@store')->name('settings.store');
});

Route::get('/home', 'Admin\HomeController@index')->name('home');
// profile
Route::get('/home/edit-profile', 'Admin\HomeController@edit')->name('profile.edit');
Route::put('/home/edit-profile', 'Admin\HomeController@update');
Route::get('/profile', 'Admin\UserController@profile')->name('profile');

// image featur
Route::get('/home/imagemanager', 'Admin\HomeController@imageManager')->name('image.manager');
// Change password
Route::get('/change-password', 'Admin\UserController@showChangePasswordForm')->name('form.change.password');
Route::post('/change-password', 'Admin\UserController@changePassword')->name('change.password');
// User
Route::resource('/home/user', 'Admin\UserController');
Route::get('/home/user/confirm/{user}', 'Admin\UserController@confirm')->name('user.confirm');
// post
Route::resource('/home/blog', 'Admin\PostController');
Route::put('/home/blog/restore/{blog}', 'Admin\PostController@restore')->name('blog.restore');
Route::delete('/home/blog/force-destroy/{blog}', 'Admin\PostController@forceDestroy')->name('blog.force-destroy');
// Category
Route::resource('/home/category', 'Admin\CategoryController');
// Project Gallery
Route::resource('/home/gallery', 'Admin\ProjectController');
// Tags
Route::get('/home/tag', 'Admin\TagController@index')->name('tag.index');
Route::delete('/home/tag/{id}', 'Admin\TagController@destroy')->name('tag.destroy');
// Comments
Route::get('/home/comment', 'Admin\CommentController@index')->name('comment.index');
Route::delete('/home/comment/{id}', 'Admin\CommentController@destroy')->name('comment.destroy');
Route::get('phpinfo', function(){
    echo phpinfo();
});

app/Models/Site/Post.php
<?php

namespace App\Models\Site;

use Carbon\Carbon;
use App\Models\Site\Tag;
use App\Models\Actor\User;
use Illuminate\Support\Facades\Config;
use Illuminate\Database\Eloquent\Model;
use GrahamCampbell\Markdown\Facades\Markdown;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    protected $fillable = ['title', 'slug', 'excerpt', 'body', 'published_at', 'category_id', 'image'];
    protected $dates = ['published_at'];

    // Merelasikan model User dengan model Post
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // Merelasikan model Category dengan model Post
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    // Merelasikan model Post dengan Tag
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    // Merelasikan model post dengan Comment
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    // Aksesor untuk konten pada artikel
    public function getBodyHtmlAttribute()
    {
        return $this->body ? Markdown::convertToHtml(e($this->body)) : NULL;
    }

    // Aksesor untuk ringkasan pada artikel
    public function getExcerptHtmlAttribute()
    {
        return $this->excerpt ? Markdown::convertToHtml(e($this->excerpt)) : NULL;
    }

    // Format Tanggal Pada Status Kolom Tabel Pos
    public function dateFormatted($showTimes = false)
    {
        $format = "d/m/Y";

        if($showTimes)
        {
            $format = $format . " H:i:s";
        }
        return $this->created_at->format($format);
    }

    // Label Penanda status publikasi artikel
    public function publicationLabel()
    {
        if(!$this->published_at)
        {
            return '<span class="label label-warning label-rounded">Draft</span>';
        }
        elseif($this->published_at && $this->published_at->isFuture())
        {
            return '<span class="label label-info label-rounded">Terjadwal</span>';
        }
        else
        {
            return '<span class="label label-success label-rounded">Diterbitkan</span>';
        }
    }

    // Aksesor untuk memanipulasi link gambar 
    public function getImageUrlAttribute()
    {

        $imageUrl = "";

        if (!is_null($this->image))
        {
            $directory = Config::get('cms.image.directory');
            $imagePath = public_path() . "/{$directory}/" . $this->image;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $this->image);
        }

        return $imageUrl;
    }

    // Aksesor untuk memanipulasi link thumbnail gambar
    public function getImageThumbUrlAttribute()
    {

        $imageUrl = "";

        if (!is_null($this->image))
        {
            $directory = Config::get('cms.image.directory');
            $ext = substr(strrchr($this->image, '.'), 1);
            $thumbnail = str_replace(".{$ext}" , "_thumb.{$ext}", $this->image);
            $imagePath = public_path() . "/{$directory}/" . $thumbnail;
            if (file_exists($imagePath)) $imageUrl = asset("{$directory}/" . $thumbnail);
        }

        return $imageUrl;
    }

    public function getDateAttribute()
    {
        return is_null($this->published_at) ? '' : $this->published_at->toFormattedDateString();
    }

    // public function getPublishedAtAttribute($value)
    // {
    //     return $this->attributes['published_at'] = $value ?: NULL;
    // }

    public function scopeLatestFirst($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function scopePopular($query)
    {
        return $query->orderBy('view_count', 'desc');
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public function scopeScheduled($query)
    {
        return $query->where("published_at", ">" , Carbon::now());
    }

    public function scopeDraft($query)
    {
        return $query->whereNull("published_at");
    }

    // Scope untuk memfilter tulisan
    public function scopeFilter($query, $filter)
    {
        if (isset($filter['month']) && $month = $filter['month']) {
            $query->whereRaw('month(published_at) = ?', [Carbon::parse($month)->month]);
            // $query->whereMonth('published_at', $month)
        }

        if (isset($filter['year']) && $year = $filter['year']) {
            $query->whereRaw('year(published_at) = ?', [$year]);
            // $query->whereYear('published_at', $year)
        }

        if(isset($filter['term']) && $term = $filter['term'])
        {
            $query->where(function($q) use($term) {

                $q->whereHas('user', function($qr) use ($term) {
                    $qr->where('name', 'LIKE', "%{$term}%");
                });

                $q->whereHas('category', function($qr) use ($term) {
                    $qr->where('title', 'LIKE', "%{$term}%");
                });

                $q->where('title', 'LIKE', "%{$term}%");
                $q->orWhere('excerpt', 'LIKE', "%{$term}%");

            });
        }
    }

    public function createTags($tagString)
    {
        $tags = explode(",", $tagString);
        $tagIds = [];
        foreach ($tags as $tag)
        {
            $newTag = new Tag();
            $newTag = Tag::firstOrCreate(
                ['slug' => str_slug($tag)], 
                ['name' => trim($tag)]);
            $newTag->slug = str_slug($tag);
            $newTag->save();
            $tagIds[] = $newTag->id;
        }
        $this->tags()->detach();
        $this->tags()->attach($tagIds);
        // option two to change detach or attach
        // $this->tags()->sync($tagIds); uncomment this
    }

    public static function archives()
    {
        return static::selectRaw('count(id) as post_count, 
                                year(published_at) year, 
                                monthname(published_at) month')
                    ->published()
                    ->groupBy('year', 'month')
                    ->orderByRaw('min(published_at) desc')
                    ->get();
    }
}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Site\Post;
use App\Models\Actor\User;
use App\Models\Site\Comment;
use App\Models\Site\Setting;
use Illuminate\Http\Request;
use App\Http\Requests\User\ProfileRequest;

class HomeController extends BaseController
{
    protected $limit = 4;
    
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $posts = Post::with('user')
        ->latestFirst()
        ->published()
        ->paginate($this->limit);

        $settings = Setting::all();

        $postsCount = Post::published()->count();

        $commentsCount = Comment::count();

        $visitorCount = Post::orderBy('view_count')->count();

        $usersCount = User::count();

        return view('backend.home.index', compact('settings', 'posts', 'postsCount', 'commentsCount', 'usersCount', 'visitorCount'));
    }

    public function imageManager()
    {
        return view('backend.imagemanager.index');
    }

    public function edit(Request $request)
    {
        $user = $request->user();

        return view('backend.home.edit', compact('user'));
    }

    public function update(ProfileRequest $request)
    {
        $user = $request->user();
        $user->update($request->all());

        return redirect()->back()->with('message', 'Profile berhasil di update');
    }
}

resources/views/backend/home/changepassword.blade.php
@extends('layouts.backend.app')
@section('title', 'Change password')
@section('content')
<body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
          <!--Header section -->
          @include('layouts.backend.navbar')
          <!-- Left side column. contains the logo and sidebar -->
          @include('layouts.backend.sidebar')
          <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Ubah
            <small>Password</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active">Ubah Password</li>
          </ol>
        </section>
        
        <!-- Main content -->
        <section class="content">
          <div class="row">
              <div class="col-md-12">
                  <!-- Widget: user widget style 1 -->
                  <div class="box box-widget widget-user">
                    <!-- Add the bg color to the header using any of the bg-* classes -->
                    <div class="widget-user-header bg-aqua-active">
                      <h3 class="widget-user-username">{{ Auth::user()->name }}</h3>
                      <h5 class="widget-user-desc">{{ Auth::user()->position }}</h5>
                    </div>
                    <div class="widget-user-image">
                      <img class="img-circle" src="{{ Auth::user()->avatar() }}" alt="User Avatar">
                    </div>
                    <div class="box-footer">
                      <div class="row">
                        <!-- /.col -->
                        <div class="col-sm-12">
                          <div class="description-block">
                            <h5 class="description-header">{{ Auth::user()->posts->count() }}</h5>
                            <span class="description-text">{{ str_plural('POST', Auth::user()->posts->count()) }}</span>
                          </div>
                          <!-- /.description-block -->
                        </div>
                        <!-- /.col -->
                      </div>
                      <!-- /.row -->
                    </div>
                  </div>
                  <!-- /.widget-user -->
              </div>
              <div class="col-md-12">
                  <!-- general form elements -->
                  <div class="box box-info">
                      <div class="box-header with-border">
                        <h3 class="box-title">Ubah Password</h3>
                      </div>
                      <form class="form-horizontal" method="POST" action="{{ route('change.password') }}">
                          {{ csrf_field() }}
                          <div class="box-body">
                              @include('backend.partial.message')
                              <div class="form-group{{ $errors->has('current-password') ? ' has-error' : '' }}">
                                  <label for="current-password" class="col-sm-2 control-label">Password Lama</label>
       
                                  <div class="col-sm-10">
                                      <input id="current-password" type="password" class="form-control" name="current-password">
       
                                      @if ($errors->has('current-password'))
                                          <span class="help-block">
                                              <strong>{{ $errors->first('current-password') }}</strong>
                                          </span>
                                      @endif
                                  </div>
                              </div>
       
                              <div class="form-group{{ $errors->has('new-password') ? ' has-error' : '' }}">
                                  <label for="new-password" class="col-sm-2 control-label">Password Baru</label>
       
                                  <div class="col-sm-10">
                                      <input id="new-password" type="password" class="form-control" name="new-password">
       
                                      @if ($errors->has('new-password'))
                                          <span class="help-block">
                                              <strong>{{ $errors->first('new-password') }}</strong>
                                          </span>
                                      @endif
                                  </div>
                              </div>
       
                              <div class="form-group">
                                  <label for="new-password-confirm" class="col-sm-2 control-label">Konfirmasi Password</label>
       
                                  <div class="col-sm-10">
                                      <input id="new-password-confirm" type="password" class="form-control" name="new-password_confirmation">
                                  </div>
                              </div>
                          </div>
                          <div class="box-footer">
                              <a href="{{ route('home') }}" class="btn btn-default">Cancel</a>
                              <button type="submit" class="btn btn-info pull-right"><i class="fa fa-refresh"></i> Ubah Password</button>
                          </div>
                      </form>
                  </div>
                  <!-- /.box -->
        
                </div>
          </div>
        </section>
        <!-- /.content -->
      </div>
      <!-- /.content-wrapper -->
        </div>
@endsection

resources/views/backend/home/edit.blade.php
@extends('layouts.backend.app')
@section('title', 'Edit profile')
@section('content')
<body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
        
          <!--Header section -->
          @include('layouts.backend.navbar')
          <!-- Left side column. contains the logo and sidebar -->
          @include('layouts.backend.sidebar')
        
          <!-- Content Wrapper. Contains page content -->
          <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
              <h1>
                Profile
                <small>Edit profile</small>
              </h1>
              <ol class="breadcrumb">
                <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">Edit profile</li>
              </ol>
            </section>
        
            <!-- Main content -->
            <section class="content">
                @if (session('message'))
                <div class="alert alert-success">
                    <p>{{ session('message') }}</p>
                </div>
                @endif
                <div class="row">
                <!-- form start -->
                {!! Form::model($user, [
                  'method' => 'PUT',
                  'url' => "/home/edit-profile",
                  'id' => 'user-form'
                  ]) !!}

                  @csrf
                  @include('backend.user.form-edit', ['hideRoleDropdown' => true])
                
                {!! Form::close() !!}
                </div>
              <!-- ./row -->
            </section>
            <!-- /.content -->
          </div>
          <!-- /.content-wrapper -->
          @include('layouts.backend.foot-note')
        
        </div>
        <!-- ./wrapper -->
        @include('backend.user.partial.script')
@endsection

resources/views/backend/home/index.blade.php
@extends('layouts.backend.app')
@section('title', 'Welcome to admin panel')
@section('content')
<body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
        
          <!--Header section -->
          @include('layouts.backend.navbar')
          <!-- Left side column. contains the logo and sidebar -->
          @include('layouts.backend.sidebar')
        
          <!-- Content Wrapper. Contains page content -->
          <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
              <h1>
                Dasbhboard
              </h1>
              <ol class="breadcrumb">
                <li class="active"><i class="fa fa-dashboard"></i> Dashboard</li>
              </ol>
            </section>
        
            <!-- Main content -->
            <section class="content">
                <div class="row">
                  <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                      <span class="info-box-icon bg-aqua"><i class="fa fa-newspaper-o"></i></span>
          
                      <div class="info-box-content">
                        <span class="info-box-text">{{ str_plural('post', $postsCount) }}</span>
                        <span class="info-box-number">{{ $postsCount }}</span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                      <span class="info-box-icon bg-red"><i class="fa fa-comment"></i></span>
          
                      <div class="info-box-content">
                        <span class="info-box-text">{{ str_plural('comment', $commentsCount) }}</span>
                        <span class="info-box-number">{{ $commentsCount }}</span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                  </div>
                  <!-- /.col -->
          
                  <!-- fix for small devices only -->
                  <div class="clearfix visible-sm-block"></div>
          
                  <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                      <span class="info-box-icon bg-green"><i class="fa fa-globe"></i></span>
          
                      <div class="info-box-content">
                        <span class="info-box-text">{{ str_plural('Visitor', $visitorCount) }}</span>
                        <span class="info-box-number">{{ $visitorCount }}</span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                  </div>
                  <!-- /.col -->
                  <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box">
                      <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>
          
                      <div class="info-box-content">
                        <span class="info-box-text">{{ str_plural('member', $usersCount) }}</span>
                        <span class="info-box-number">{{ $usersCount }}</span>
                      </div>
                      <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                  </div>
                  <!-- /.col -->
                  <div class="col-xs-12">
                    <div class="box box-info">
                      <div class="box-header">
                          <div class="pull-right box-tools">
                              <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                                  <i class="fa fa-minus"></i></button>
                              <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
                                  <i class="fa fa-times"></i></button>
                          </div>
                      </div>
                      <!-- /.box-header -->
                      <div class="box-body ">
                            <h3><i class="fa fa-flag"></i> Welcome to {{ \setting('app_name') }}!</h3>
                            <p class="lead text-muted">Hallo {{Auth::user()->name}}, Welcome to {{ \setting('app_name') }}</p>
        
                            <h4>Get started</h4>
                            <p><a href="{{ route('blog.create') }}" class="btn btn-primary">Tulis artikel <i class="fa fa-pencil"></i> </a> </p>
                      </div>
                      <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                  </div>
                  {{-- <div class="col-xs-12">
                      <div class="box box-info">
                          <div class="box-header with-border">
                            <h3 class="box-title"><i class="fa fa-newspaper-o"></i> Artikel produk terbaru</h3>
                            <div class="pull-right box-tools">
                                <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                                    <i class="fa fa-minus"></i></button>
                                <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
                                    <i class="fa fa-times"></i></button>
                            </div>
                          </div>
                          <!-- /.box-header -->
                          <div class="box-body">
                            <ul class="products-list product-list-in-box">
                              @forelse ($posts as $post)
                              <li class="item">
                                  <div class="product-img">
                                    @if ($post->image_url)
                                    <img src="{{ $post->image_url }}" alt="{{ $post->title }}">
                                    @else
                                    <img src="/frontend/images/about.jpg" alt="{{ $post->title }}">
                                    @endif
                                  </div>
                                  <div class="product-info">
                                    <a href="javascript:void(0)" class="product-title">{{ $post->title }}
                                      <span class="label label-default pull-right">{{ $post->category->title }}</span></a>
                                    <span class="product-description">
                                          {!! str_limit($post->excerpt, 100) !!}
                                    </span>
                                  </div>
                                </li>
                                <!-- /.item -->
                              @empty
                                  Tidak ada daftar produk yang ditemukan.
                              @endforelse
                            </ul>
                          </div>
                          <!-- /.box-body -->
                        </div>
                  </div> --}}
                  @role('admin')
                  <div class="col-xs-12">
                    <div class="box box-info">
                      <!-- /.box-header -->
                          <div class="box-header with-border">
                            <h3 class="box-title">
                                <i class="fa fa-wrench"></i> Pengaturan Website
                            </h3>
                            <div class="pull-right box-tools">
                                <a href="{{ route('settings') }}" class="btn btn-info btn-sm" data-toggle="tooltip" title="" data-original-title="Edit">
                                    <i class="fa fa-edit"></i></a>
                                <button type="button" class="btn btn-info btn-sm" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                                    <i class="fa fa-minus"></i></button>
                                <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
                                    <i class="fa fa-times"></i></button>
                            </div>
                          </div>
                          <div class="box-body table-responsive no-padding">
                              <table class="table table-bordered table-striped table-hover">
                                  <tr class="info">
                                      <th>Pengaturan</th>
                                      <th>Aksesor</th>
                                      <th>Nilai</th>
                                  </tr>
                                  @forelse($settings as $setting)
                                  <tr>
                                      <td>{{ $setting->name }}</td>
                                      <td><span class="label label-info">\setting('{{ $setting->name }}')</span></td>
                                      <td>{{ $setting->val }}</td>
                                  </tr>
                                      @empty
                                  <tr>
                                      <td colspan="3" class="text-center">Tidak ada pengaturan aplikasi yang tersimpan.</td>
                                  </tr>
                                  @endforelse
                              </table>
                          </div>
                      <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                  </div>
                  @endrole
                </div>
              <!-- ./row -->
            </section>
            <!-- /.content -->
          </div>
          <!-- /.content-wrapper -->
          @include('layouts.backend.foot-note')
        
        </div>
        <!-- ./wrapper -->
@endsection